name: Docker Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'production' || null }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set variables
        run: |
          echo "GIT_SHA1=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
          echo "CURRENT_VERSION=$(cat current-version)" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        if: github.ref_name == 'master'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref_name == 'master' }}
          tags: hpello/tcp-proxy:${{ env.CURRENT_VERSION }}-${{ env.GIT_SHA1 }}, hpello/tcp-proxy:${{ env.CURRENT_VERSION }}, hpello/tcp-proxy:latest
          platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64
