name: Docker Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          # Fetch tag information
          fetch-depth: 0
      - name: Set variables
        run: |
          echo "GIT_SHA1=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
          echo "GIT_TAG=$(git describe --tags --abbrev=0 | sed s/v//g)" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        if: github.ref_name == 'master'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref_name == 'master' }}
          tags: hpello/tcp-proxy:${{ env.GIT_SHA1 }}, hpello/tcp-proxy:${{ env.GIT_TAG }}
          platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64
